/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    UBtn: typeof import('uno-vui')['UnoBtn']
    UnoBtn: typeof import('uno-vui')['UnoBtn']
  }
}
