/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    UBtn: typeof import('uno-vui')['UBtn']
    UIcon: typeof import('uno-vui')['UIcon']
    UInput: typeof import('uno-vui')['UInput']
    UThemePick: typeof import('uno-vui')['UThemePick']
  }
}
